PROG = ParallelCompressorTest
PROG_VALIDATION = ParallelCompressorValidation
PROG_E2E = ParallelE2ETest
PROG_PARITY = ParallelFeatureParityTest
PROG_INTEGRATION = ParallelIntegrationTest
PROG_SOLID_MULTIVOLUME = ParallelSolidMultiVolumeTest
PROG_SECURITY = ParallelSecurityTest
CXX = g++
CXXFLAGS = -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DNDEBUG
LDFLAGS = -lpthread

OBJS = \
  ParallelCompressorTest.o \
  ParallelCompressor.o \
  ParallelCompressAPI.o \
  ParallelCompressorRegister.o \

OBJS_VALIDATION = \
  ParallelCompressorValidation.o \
  ParallelCompressor.o \
  ParallelCompressAPI.o \
  ParallelCompressorRegister.o \

OBJS_E2E = \
  ParallelE2ETest.o \
  ParallelCompressor.o \
  ParallelCompressAPI.o \
  ParallelCompressorRegister.o \

OBJS_PARITY = \
  ParallelFeatureParityTest.o \
  ParallelCompressor.o \
  ParallelCompressAPI.o \
  ParallelCompressorRegister.o \

OBJS_INTEGRATION = \
  ParallelIntegrationTest.o \
  ParallelCompressor.o \
  ParallelCompressAPI.o \
  ParallelCompressorRegister.o \

OBJS_SOLID_MULTIVOLUME = \
  ParallelSolidMultiVolumeTest.o \
  ParallelCompressor.o \
  ParallelCompressAPI.o \
  ParallelCompressorRegister.o \

OBJS_SECURITY = \
  ParallelSecurityTest.o \
  ParallelCompressor.o \
  ParallelCompressAPI.o \
  ParallelCompressorRegister.o \

COMMON_OBJS = \
  ../../Common/MyString.o \
  ../../Common/IntToString.o \
  ../../Common/StringConvert.o \
  ../../Common/MyVector.o \
  ../../Common/MyWindows.o \

WINDOWS_OBJS = \
  ../../Windows/FileDir.o \
  ../../Windows/FileFind.o \
  ../../Windows/FileIO.o \
  ../../Windows/FileName.o \
  ../../Windows/PropVariant.o \
  ../../Windows/Synchronization.o \
  ../../Windows/System.o \
  ../../Windows/Thread.o \

COMPRESS_OBJS = \
  ../Common/InBuffer.o \
  ../Common/OutBuffer.o \
  ../Common/StreamUtils.o \
  ../Common/FileStreams.o \
  ../Common/StreamObjects.o \
  ../Common/LimitedStreams.o \
  ../Common/MethodProps.o \
  ../Common/RegisterCodec.o \
  ../Common/CreateCoder.o \
  LzmaEncoder.o \
  Lzma2Encoder.o \

C_OBJS = \
  ../../../C/Alloc.o \
  ../../../C/LzFind.o \
  ../../../C/LzmaEnc.o \
  ../../../C/Lzma2Enc.o \
  ../../../C/Threads.o \

all: $(PROG) $(PROG_VALIDATION) $(PROG_E2E) $(PROG_PARITY) $(PROG_INTEGRATION) $(PROG_SOLID_MULTIVOLUME) $(PROG_SECURITY)

$(PROG): $(OBJS) $(COMMON_OBJS) $(WINDOWS_OBJS) $(COMPRESS_OBJS) $(C_OBJS) StdAfx.o
	$(CXX) -o $(PROG) $^ $(LDFLAGS)

$(PROG_VALIDATION): $(OBJS_VALIDATION) $(COMMON_OBJS) $(WINDOWS_OBJS) $(COMPRESS_OBJS) $(C_OBJS) StdAfx.o
	$(CXX) -o $(PROG_VALIDATION) $^ $(LDFLAGS)

$(PROG_E2E): $(OBJS_E2E) $(COMMON_OBJS) $(WINDOWS_OBJS) $(COMPRESS_OBJS) $(C_OBJS) StdAfx.o
	$(CXX) -o $(PROG_E2E) $^ $(LDFLAGS)

$(PROG_PARITY): $(OBJS_PARITY) $(COMMON_OBJS) $(WINDOWS_OBJS) $(COMPRESS_OBJS) $(C_OBJS) StdAfx.o
	$(CXX) -o $(PROG_PARITY) $^ $(LDFLAGS)

$(PROG_INTEGRATION): $(OBJS_INTEGRATION) $(COMMON_OBJS) $(WINDOWS_OBJS) $(COMPRESS_OBJS) $(C_OBJS) StdAfx.o
	$(CXX) -o $(PROG_INTEGRATION) $^ $(LDFLAGS)

$(PROG_SOLID_MULTIVOLUME): $(OBJS_SOLID_MULTIVOLUME) $(COMMON_OBJS) $(WINDOWS_OBJS) $(COMPRESS_OBJS) $(C_OBJS) StdAfx.o
	$(CXX) -o $(PROG_SOLID_MULTIVOLUME) $^ $(LDFLAGS)

$(PROG_SECURITY): $(OBJS_SECURITY) $(COMMON_OBJS) $(WINDOWS_OBJS) $(COMPRESS_OBJS) $(C_OBJS) StdAfx.o
	$(CXX) -o $(PROG_SECURITY) $^ $(LDFLAGS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(PROG) $(PROG_VALIDATION) $(PROG_E2E) $(PROG_PARITY) $(PROG_INTEGRATION) $(PROG_SOLID_MULTIVOLUME) $(PROG_SECURITY) *.o ../../Common/*.o ../../Windows/*.o ../Common/*.o ../../../C/*.o
	rm -f test_*.7z test_file*.txt

test: $(PROG) $(PROG_VALIDATION) $(PROG_E2E) $(PROG_PARITY) $(PROG_INTEGRATION) $(PROG_SOLID_MULTIVOLUME) $(PROG_SECURITY)
	./$(PROG)
	./$(PROG_VALIDATION)
	./$(PROG_E2E)
	./$(PROG_PARITY)
	./$(PROG_INTEGRATION)
	./$(PROG_SOLID_MULTIVOLUME)
	./$(PROG_SECURITY)

.PHONY: all clean test
